def song(action, action2, action3, pronoun, date, number, action4, action5):
    print(f"take on {pronoun}")
    print(f"We're {action} away")
    print(f"I don't know what I'm to {action2}")
    print(f"I'll {action2} it anyway")
    print(f"{date} is another day to find you")
    print(f"{action5}' away")
    print(f"Oh, I'll be coming' for your love, okay")
    print(f"{action3} on {pronoun})")
    print(f"({action3} on {pronoun})")
    print(f"{action3} {pronoun} on")
    print(f"({action3} on {pronoun})")
    print(f"I'll be gone")
    print(f"In a day or {number}")
    print(f"So needless to {action2}")
    print(f"I'm odds and ends")
    print(f"But I'll be stumbling' away")
    print(f"Slowly learnin' that life is okay")
    print(f"{action2} after {pronoun}")
    print(f"It's no better to be safe than sorry")
    print(f"{action3} on {pronoun}")
    print(f"({action3} on {pronoun})")
    print(f"{action3} {pronoun} on")
    print(f"({action3} on {pronoun})")
    print(f"I'll be gone")
    print(f"In a day or {pronoun}")
    print(f"All the things that you {action2}, yeah")
    print(f"Is it life or just to play my worries away?")
    print(f"You're all the things I've got to remember")
    print(f"You're {action5}' away")
    print(f"I'll be {action4}' for you anyway")
    print(f"{action3} on {pronoun}")
    print(f"({action3} on {pronoun})")
    print(f"({action3} {pronoun} on)")
    print(f"({action3} on {pronoun})")
    print(f"({action3} on {pronoun})")
    print(f"({action3} on {pronoun})")
    print(f"({action3} {pronoun} on)")
    print(f"({action3} on {pronoun})")


action = input("give me a action: ")
action2 = input("give me another action: ")
number = input("give a number: ")
action3 = input("give me another action: ")
date = input("give me a date: ")
action4 = input("give me another action: ")
pronoun = input("give me a pronoun: ")
action5 = input("give me another action: ")

song(action, action2, action3, action4, action5, number, pronoun, date)
